### ISSUE TITLE
panorama_latest.gz unavailable

### ISSUE THREAD

**Issue by mfromholtz** [Amsterdam/panorama#37]
Hello,

I tried following your notes in order to run an instance of panorama on a local server. I can get the docker image amsterdam/postgres11 but when I run this command : 

`docker-compose exec database update-db.sh panorama <your_username>`

I've got this message : 

![image](https://user-images.githubusercontent.com/65349061/81946646-e9cdd000-95ff-11ea-8b77-2f46cbd6aece.png)

Maybe there is some things I don't get yet. I used google translate for understanding your readme since I can't read Flemish, sorry.

Thanks in advance.

**Comment by lbam** [comment]
This is only available in our internal network.
